### ISSUE TITLE
latest update of mono-d requires MonoDevelop v6

### ISSUE THREAD

**Issue by sycam0inc** [aBothe/Mono-D#604] opened 2015-04-25 07:53 UTC
not only The latest stable release of MonoDevelop is 5.7.0
I cant even find any mention of MonoDevelop or Xamarin 6 the latest beta is 5.9
This is a real issue because because Xamarin studio is my primary D editor

**Comment by aBothe** [comment] 2015-04-25 08:02
Gonna fix it, hold on.

**Comment by aBothe** [comment] 2015-04-25 08:14
With 2.11.3, it should be fixed.

**Closed** 2015-04-25 17:40 UTC

**Comment by Valera** [comment] 2015-07-10 10:19
Strangely, with Monodevelop 6.0 on Ubuntu 14.10 latest Mono-D add-ins do not load and require Monodevelop 5.0. Manually downloaded version 2.11.2 works fine.

**Comment by aBothe** [comment] 2015-07-10 17:09
I still release Mono-D with MonoDevelop 5.0 dependencies because there still is MonoDevelop 5.0 stable out there.
As soon as 6.0 gets released, I'll push the 6.0 dependencies on to the repo as well.
So for now, just downgrade your MonoDevelop to 5.9 or so, it'll be just fine for taking a look at Mono-D.

**Comment by Valera** [comment] 2015-07-10 17:42
The problem is, the link http://simendsjo.me/files/abothe at official Mono-D page already points to v6.0 and there is no mentions of downgrade there.

**Comment by aBothe** [comment] 2015-07-11 07:16
Yeah, that's an inconsistency. I just..well, should do a second branch, for 5.0 releases.

**Comment by aBothe** [comment] 2015-07-11 07:19
I made an `md60` branch for 6.0 releases. Keeps things easier.

**Comment by aBothe** [comment] 2015-07-23 18:55
@Valera the latest build of MonoDevelop is 5.10 again. They must've downgraded the version again, probably because they delayed the actual 6 overhaul for another while :smile:
